### ISSUE TITLE
Allowed memory exhaused when wallet transaction history is too large

### ISSUE THREAD

**Issue by cnukaus** [XDagger/explorer#2]
https://explorer.xdag.io/block/WLYMhgmO01vA86yfdk7bEMX2lqzFxalj
![image](https://user-images.githubusercontent.com/5101195/40876794-3d685d4e-66bd-11e8-9510-d25ce2d3b55c.png)

**Comment by kbs1** [comment]
Hi, I know, please wait for a new version of explorer, I'm preparing it fron scratch with many useful features such as graphs per address, earnings, spent, filtering by date, with fancy graphics (more like xdag.io), rewritten from scratch in laravel, with real pagning (don't load all into memory) and with searching in transactions / addresses etc, so many new features, that version won't have this problem, as it uses a new parser :) ETA to be done 2 weeks max

**Comment by kbs1** [comment]
@cnukaus solved with the new block exploer :)

**Comment by cnukaus** [comment]
amazing job kbs1!
